export {
  generateUUID,
  generateRoomCode,
  createPlayer,
  shuffleArray,
  createFullDeck,
  sortHand,
  getCardsPerPlayer,
  createTrio,
  isValidTrio,
  checkVictoryConditions,
  getSmallestCard,
  getLargestCard,
  hasTwoDifferentNumbers,
  hasTwoConsecutiveDifferentNumbers,
  extractNumbers,
  allSameNumber,
  getNextPlayer,
  createInitialGameState,
  calculateAIDelay,
} from '../../../shared/src/utils/helpers.js';

export {
  validateCard,
  validateTrio,
  validatePlayer,
  validateGameAction,
  validateGameState,
  validateRoomSettings,
  validateRoomInfo,
  validateCardIntegrity,
  isValidUUID,
} from '../../../shared/src/utils/validation.js';
